# Generated by Django 5.1.1 on 2025-02-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'Food Product'), ('beauty', 'Beauty Product')], max_length=10)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients_text', models.TextField()),
                ('ingredients_image', models.ImageField(blank=True, null=True, upload_to='ingredients_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_json', models.JSONField()),
                ('overall_rating', models.IntegerField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyzer.product')),
            ],
        ),
    ]
